version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: pasit/ex-opencv-nodejs
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build-src:
    docker:
      - image: pasit/opencv-nodejs-base
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-lib-dist-{{ checksum "lib/yarn.lock" }}
      - run:
          name: Build Lib
          command: |
              cd lib
              yarn
              yarn run build
              cd ..
      - save_cache:
          key: v1-lib-dist-{{ checksum "lib/yarn.lock" }}
          paths:
            - lib/node_modules
            - lib/dist
      - restore_cache:
          keys:
            - v1-node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Build node_modules
          command: yarn
      - save_cache:
          key: v1-node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build src
          command: yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - dist
            - lib
            - package.json
            - yarn.lock
            - moleculer.config.js
            - Dockerfile
  build-img:
    executor: docker-publisher
    working_directory: /tmp/workspace
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true 
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME:latest


workflows:
  version: 2
  build-master:
    jobs:
      - build-src:
          filters:
            branches:
              only: master
      - build-img:
          requires:
            - build-src
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build-img
          filters:
            branches:
              only: master